In [44]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [33]:
data = [
    {"sentence": "The movie was fantastic and I enjoyed every moment.", "label": "positive"},
    {"sentence": "The food tasted amazing and the service was excellent.", "label": "positive"},
    {"sentence": "I am very happy with the product quality and delivery speed.", "label": "positive"},
    {"sentence": "My experience at the hotel was wonderful and relaxing.", "label": "positive"},
    {"sentence": "The staff were friendly and helped me quickly.", "label": "positive"},
    {"sentence": "The new phone is fast, reliable, and easy to use.", "label": "positive"},
    {"sentence": "This book was inspiring and beautifully written.", "label": "positive"},
    {"sentence": "I loved the design and the overall performance.", "label": "positive"},
    {"sentence": "The appointment was on time and the doctor was great.", "label": "positive"},
    {"sentence": "The event was well organized and very enjoyable.", "label": "positive"},
    {"sentence": "The product arrived late and the packaging was damaged.", "label": "negative"},
    {"sentence": "I am disappointed with the customer service response time.", "label": "negative"},
    {"sentence": "The app keeps crashing and is difficult to navigate.", "label": "negative"},
    {"sentence": "The room was dirty and the staff were unhelpful.", "label": "negative"},
    {"sentence": "The food was bland and the portions were too small.", "label": "negative"},
    {"sentence": "The delivery was delayed and the order was incorrect.", "label": "negative"},
    {"sentence": "I regret buying this product because it broke quickly.", "label": "negative"},
    {"sentence": "The website is slow and full of annoying popups.", "label": "negative"},
    {"sentence": "The lecture was boring and the material was unclear.", "label": "negative"},
    {"sentence": "The experience was frustrating and did not meet expectations.", "label": "negative"},
]

df = pd.DataFrame(data,)

df =  df.sample(frac= 1).reset_index(drop= True)

print(df)

                                             sentence     label
0    The website is slow and full of annoying popups.  negative
1   The lecture was boring and the material was un...  negative
2   The movie was fantastic and I enjoyed every mo...  positive
3   The appointment was on time and the doctor was...  positive
4   The app keeps crashing and is difficult to nav...  negative
5   My experience at the hotel was wonderful and r...  positive
6   I am very happy with the product quality and d...  positive
7   The delivery was delayed and the order was inc...  negative
8   I am disappointed with the customer service re...  negative
9    This book was inspiring and beautifully written.  positive
10   The room was dirty and the staff were unhelpful.  negative
11  The food tasted amazing and the service was ex...  positive
12  The experience was frustrating and did not mee...  negative
13  The new phone is fast, reliable, and easy to use.  positive
14  The food was bland and the portions were too s...  negative
15    I loved the design and the overall performance.  positive
16  The product arrived late and the packaging was...  negative
17     The staff were friendly and helped me quickly.  positive
18  I regret buying this product because it broke ...  negative
19   The event was well organized and very enjoyable.  positive

In [15]:
X = df['sentence']
Y = df['label']

In [16]:
count_vec = CountVectorizer()

sparse_matrix = count_vec.fit_transform(X)
bag_of_words =  pd.DataFrame(sparse_matrix.toarray(), columns= count_vec.get_feature_names_out())
print(bag_of_words)

    am  amazing  and  annoying  app  appointment  arrived  at  beautifully  \
0    0        0    1         1    0            0        0   0            0
1    0        0    1         0    0            0        0   0            0
2    0        0    1         0    0            0        0   1            0
3    0        0    0         0    0            0        0   0            0
4    0        0    1         0    0            0        0   0            0
5    0        0    1         0    0            0        0   0            0
6    0        0    1         0    0            1        0   0            0
7    0        0    1         0    0            0        0   0            0
8    0        0    1         0    0            0        0   0            0
9    0        0    1         0    0            0        0   0            0
10   0        0    1         0    0            0        1   0            0
11   0        0    1         0    0            0        0   0            0
12   1        0    1         0    0            0        0   0            0
13   0        0    1         0    0            0        0   0            1
14   0        1    1         0    0            0        0   0            0
15   1        0    0         0    0            0        0   0            0
16   0        0    1         0    1            0        0   0            0
17   0        0    1         0    0            0        0   0            0
18   0        0    1         0    0            0        0   0            0
19   0        0    1         0    0            0        0   0            0

    because  ...  unhelpful  use  very  was  website  well  were  with  \
0         0  ...          0    0     0    0        1     0     0     0
1         0  ...          0    0     0    2        0     0     0     0
2         0  ...          0    0     0    1        0     0     0     0
3         1  ...          0    0     0    0        0     0     0     0
4         0  ...          0    1     0    0        0     0     0     0
5         0  ...          0    0     0    1        0     0     1     0
6         0  ...          0    0     0    2        0     0     0     0
7         0  ...          0    0     0    0        0     0     1     0
8         0  ...          0    0     0    1        0     0     0     0
9         0  ...          0    0     0    1        0     0     0     0
10        0  ...          0    0     0    1        0     0     0     0
11        0  ...          0    0     0    0        0     0     0     0
12        0  ...          0    0     1    0        0     0     0     1
13        0  ...          0    0     0    1        0     0     0     0
14        0  ...          0    0     0    1        0     0     0     0
15        0  ...          0    0     0    0        0     0     0     1
16        0  ...          0    0     0    0        0     0     0     0
17        0  ...          0    0     1    1        0     1     0     0
18        0  ...          0    0     0    2        0     0     0     0
19        0  ...          1    0     0    1        0     0     1     0

    wonderful  written
0           0        0
1           0        0
2           1        0
3           0        0
4           0        0
5           0        0
6           0        0
7           0        0
8           0        0
9           0        0
10          0        0
11          0        0
12          0        0
13          0        1
14          0        0
15          0        0
16          0        0
17          0        0
18          0        0
19          0        0

[20 rows x 101 columns]

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(bag_of_words, Y, test_size= 0.3, random_state= 7)

In [20]:
print(X_test)

    am  amazing  and  annoying  app  appointment  arrived  at  beautifully  \
1    0        0    1         0    0            0        0   0            0
17   0        0    1         0    0            0        0   0            0
2    0        0    1         0    0            0        0   1            0
5    0        0    1         0    0            0        0   0            0
11   0        0    1         0    0            0        0   0            0
0    0        0    1         1    0            0        0   0            0

    because  ...  unhelpful  use  very  was  website  well  were  with  \
1         0  ...          0    0     0    2        0     0     0     0
17        0  ...          0    0     1    1        0     1     0     0
2         0  ...          0    0     0    1        0     0     0     0
5         0  ...          0    0     0    1        0     0     1     0
11        0  ...          0    0     0    0        0     0     0     0
0         0  ...          0    0     0    0        1     0     0     0

    wonderful  written
1           0        0
17          0        0
2           1        0
5           0        0
11          0        0
0           0        0

[6 rows x 101 columns]

In [24]:
lr = LogisticRegression(random_state= 1).fit(X_train,Y_train)

In [26]:
y_predict_lr = lr.predict(X_test)
accuracy_score(y_predict_lr, Y_test)

0.3333333333333333

In [27]:
y_predict_lr

array(['negative', 'positive', 'negative', 'positive', 'negative',
       'positive'], dtype=object)

In [28]:
Y_test

1     negative
17    positive
2     positive
5     negative
11    positive
0     negative
Name: label, dtype: object

In [30]:
print(classification_report(Y_test, y_predict_lr, zero_division= 0))

              precision    recall  f1-score   support

    negative       0.33      0.33      0.33         3
    positive       0.33      0.33      0.33         3

    accuracy                           0.33         6
   macro avg       0.33      0.33      0.33         6
weighted avg       0.33      0.33      0.33         6

In [48]:
game_classification = [
    {"sentence": "Outlast has an amazing atmosphere and kept me on edge all night.", "label": "Outlast"},
    {"sentence": "The jumpscares in Outlast are terrifying and very well timed.", "label": "Outlast"},
    {"sentence": "Outlast's story was creepy and deeply immersive.", "label": "Outlast"},
    {"sentence": "I loved the dark, abandoned asylum setting in Outlast.", "label": "Outlast"},
    {"sentence": "Outlast delivered one of the most frightening horror experiences I've played.", "label": "Outlast"},
    {"sentence": "Outlast felt too repetitive after a few hours of running and hiding.", "label": "Outlast"},
    {"sentence": "The game mechanics in Outlast are limited, and the camera control is awkward.", "label": "Outlast"},
    {"sentence": "Outlast's ending was confusing and left too many questions unanswered.", "label": "Outlast"},
    {"sentence": "I found Outlast too reliant on loud noises instead of real suspense.", "label": "Outlast"},
    {"sentence": "Outlast was frustrating because the stealth sections felt unfair.", "label": "Outlast"},
    {"sentence": "Condemned: Criminal Origins has an intense beat-em-up combat system.", "label": "Condemned: Criminal Origins"},
    {"sentence": "The investigation sections in Condemned are atmospheric and satisfying.", "label": "Condemned: Criminal Origins"},
    {"sentence": "Condemned's sound design makes every alley feel dangerous and alive.", "label": "Condemned: Criminal Origins"},
    {"sentence": "I really enjoyed the gritty detective story in Condemned.", "label": "Condemned: Criminal Origins"},
    {"sentence": "Condemned creates a great sense of tension with its close-quarters fights.", "label": "Condemned: Criminal Origins"},
    {"sentence": "The reproduction of old-school horror in Condemned feels dated at times.", "label": "Condemned: Criminal Origins"},
    {"sentence": "Condemned's camera and movement can be clunky during fights.", "label": "Condemned: Criminal Origins"},
    {"sentence": "Some enemies in Condemned are too hard to see in the dark environments.", "label": "Condemned: Criminal Origins"},
    {"sentence": "I got bored by the repetitive combat in Condemned after a while.", "label": "Condemned: Criminal Origins"},
    {"sentence": "The story pacing in Condemned dragged and made the game feel slower than it should.", "label": "Condemned: Criminal Origins"},
]

pd_game_classification = pd.DataFrame(game_classification)
pd_game_classification = pd_game_classification.sample(frac= 1).reset_index(drop= True)
print(pd_game_classification)

                                             sentence  \
0   The investigation sections in Condemned are at...
1   The story pacing in Condemned dragged and made...
2   Outlast's ending was confusing and left too ma...
3   Condemned: Criminal Origins has an intense bea...
4   Outlast felt too repetitive after a few hours ...
5   Condemned's sound design makes every alley fee...
6   Condemned's camera and movement can be clunky ...
7   Outlast was frustrating because the stealth se...
8   The jumpscares in Outlast are terrifying and v...
9   Outlast delivered one of the most frightening ...
10  The reproduction of old-school horror in Conde...
11  I found Outlast too reliant on loud noises ins...
12  Condemned creates a great sense of tension wit...
13  I got bored by the repetitive combat in Condem...
14  Some enemies in Condemned are too hard to see ...
15  I loved the dark, abandoned asylum setting in ...
16  Outlast has an amazing atmosphere and kept me ...
17  The game mechanics in Outlast are limited, and...
18   Outlast's story was creepy and deeply immersive.
19  I really enjoyed the gritty detective story in...

                          label
0   Condemned: Criminal Origins
1   Condemned: Criminal Origins
2                       Outlast
3   Condemned: Criminal Origins
4                       Outlast
5   Condemned: Criminal Origins
6   Condemned: Criminal Origins
7                       Outlast
8                       Outlast
9                       Outlast
10  Condemned: Criminal Origins
11                      Outlast
12  Condemned: Criminal Origins
13  Condemned: Criminal Origins
14  Condemned: Criminal Origins
15                      Outlast
16                      Outlast
17                      Outlast
18                      Outlast
19  Condemned: Criminal Origins

In [49]:
X = pd_game_classification['sentence']
Y = pd_game_classification['label']

In [50]:
tfidfVectorizer = TfidfVectorizer()

sparse_matrix = tfidfVectorizer.fit_transform(X)
tf_X = pd.DataFrame(sparse_matrix.toarray(), columns= tfidfVectorizer.get_feature_names_out())
tf_X

,abandoned,after,alive,all,alley,amazing,an,and,are,asylum,...,too,unanswered,unfair,up,ve,very,was,well,while,with
0,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.214023,0.316505,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.149550,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.177758,0.000000,0.000000,...,0.262874,0.36179,0.000000,0.000000,0.000000,0.000000,0.286963,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.284303,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.323433,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.315130,0.00000,0.000000,0.00000,0.000000,0.000000,0.176143,0.000000,0.000000,...,0.260486,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.34804,0.000000,0.34804,0.000000,0.000000,0.171002,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.185333,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.388297,0.000000,0.000000,0.000000,0.307987,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.192753,0.285049,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.392309,0.000000,0.392309,0.000000,0.000000
9,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.339374,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.242280,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.325026
13,0.000000,0.331147,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.376725,0.000000
14,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.237404,0.000000,...,0.237404,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.426371,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.426371,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.00000,0.319425,0.00000,0.319425,0.280780,0.156943,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.166648,0.246444,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.225650,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.364277,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [51]:
X_train, X_test, Y_train, Y_test = train_test_split(tf_X, Y, test_size= 0.4, random_state= 7)
X_test

,abandoned,after,alive,all,alley,amazing,an,and,are,asylum,...,too,unanswered,unfair,up,ve,very,was,well,while,with
1,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.149550,0.000000,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
17,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.166648,0.246444,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.177758,0.000000,0.0,...,0.262874,0.36179,0.0,0.0,0.0,0.0,0.286963,0.0,0.0,0.0
5,0.0,0.0,0.34804,0.0,0.34804,0.0,0.0,0.171002,0.000000,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
11,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.0,...,0.242280,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
0,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.214023,0.316505,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
18,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.225650,0.000000,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.364277,0.0,0.0,0.0
6,0.0,0.0,0.00000,0.0,0.00000,0.0,0.0,0.185333,0.000000,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0