In [5]:
!pip install spacy
!python -m spacy download en_core_web_sm

'pip' is not recognized as an internal or external command,
operable program or batch file.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Apps > Advanced app settings > App execution aliases.

In [6]:
import spacy
import pandas as pd
import re

ModuleNotFoundError: No module named 'spacy'

In [6]:
nlp = spacy.load('en_core_web_sm')

In [7]:
para = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"

print(para)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [8]:
spacy_doc = nlp(para)

print(spacy_doc)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [19]:
pos_df =  pd.DataFrame(columns = ["token" , "pos_tag"])


for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{"token" : token.text, "pos_tag" : token.pos_}])],ignore_index = True)

In [20]:
pos_df.head(15)

          token pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [26]:
pos_df_counts = pos_df.groupby(["token", "pos_tag"]).size().reset_index(name = "count").sort_values(by = "count" , ascending = False)
pos_df_counts.head(15)

         token pos_tag  count
88          of     ADP     14
49         had     AUX      9
54         her    PRON      9
111        the     DET      8
6          and   CCONJ      8
0            a     DET      6
114         to    PART      5
61          in     ADP      4
13        been     AUX      4
120       very     ADV      4
48   governess    NOUN      3
46      friend    NOUN      3
125       with     ADP      2
5           an     DET      2
130      years    NOUN      2

In [33]:
pos_df_poscounts = pos_df_counts.groupby(["pos_tag"])["token"].count().sort_values(ascending = False)

pos_df_poscounts.head(15)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
NUM       3
SCONJ     3
PART      1
Name: token, dtype: int64

In [40]:
noun = pos_df_counts[pos_df_counts.pos_tag == "NOUN"][0:10]
noun

         token pos_tag  count
48   governess    NOUN      3
46      friend    NOUN      3
130      years    NOUN      2
35        emma    NOUN      2
28   daughters    NOUN      2
103    sisters    NOUN      2
82      mother    NOUN      2
89      office    NOUN      1
78    mistress    NOUN      1
75    mildness    NOUN      1

In [37]:
verbs = pos_df_counts[pos_df_counts.pos_tag == "VERB"][0:10].sort_values( by = "count", ascending = False)
verbs

        token pos_tag  count
93     passed    VERB      1
77       miss    VERB      1
119     unite    VERB      1
106  supplied    VERB      1
99     seemed    VERB      1
72     living    VERB      1
33      doing    VERB      1
30   directed    VERB      1
29       died    VERB      1
23     ceased    VERB      1

In [41]:
paragraph = "Middle-earth: Shadow of Mordor is a third-person open world action-adventure video game, where the player controls a ranger by the name of Talion who seeks revenge on the forces of Sauron after his family, consisting of his wife and son, are killed by those that lead them.[1] Players can travel across locations in the game through parkour, riding monsters, or accessing Forge Towers, which serve as fast travel points.[2][3] Though Talion is mortally felled in the game's introduction, the wraith of the Elven Lord Celebrimbor is able to use his power to keep Talion alive, along with gifting him wraith-like abilities.[4] Missions in the game feature main story missions that follow Talion's quest for revenge, side missions that involve following Gollum to find artifacts that are tied to Celebrimbor's past, missions to free the human slaves that have been captured by the Uruk armies and forced to work for Sauron, and additional quests to help forge new abilities for Talion's sword, bow, and dagger.[5][6][7] The player also has the freedom to pursue side quests and roam around Mordor, with special activities to collect specific flora or to hunt certain creatures, or to find old artifacts or Elvish seals.[8][9]"

paragraph

"Middle-earth: Shadow of Mordor is a third-person open world action-adventure video game, where the player controls a ranger by the name of Talion who seeks revenge on the forces of Sauron after his family, consisting of his wife and son, are killed by those that lead them.[1] Players can travel across locations in the game through parkour, riding monsters, or accessing Forge Towers, which serve as fast travel points.[2][3] Though Talion is mortally felled in the game's introduction, the wraith of the Elven Lord Celebrimbor is able to use his power to keep Talion alive, along with gifting him wraith-like abilities.[4] Missions in the game feature main story missions that follow Talion's quest for revenge, side missions that involve following Gollum to find artifacts that are tied to Celebrimbor's past, missions to free the human slaves that have been captured by the Uruk armies and forced to work for Sauron, and additional quests to help forge new abilities for Talion's sword, bow, and dagger.[5][6][7] The player also has the freedom to pursue side quests and roam around Mordor, with special activities to collect specific flora or to hunt certain creatures, or to find old artifacts or Elvish seals.[8][9]"

In [44]:
paragraph = paragraph.lower()
paragraph

"middle-earth: shadow of mordor is a third-person open world action-adventure video game, where the player controls a ranger by the name of talion who seeks revenge on the forces of sauron after his family, consisting of his wife and son, are killed by those that lead them.[1] players can travel across locations in the game through parkour, riding monsters, or accessing forge towers, which serve as fast travel points.[2][3] though talion is mortally felled in the game's introduction, the wraith of the elven lord celebrimbor is able to use his power to keep talion alive, along with gifting him wraith-like abilities.[4] missions in the game feature main story missions that follow talion's quest for revenge, side missions that involve following gollum to find artifacts that are tied to celebrimbor's past, missions to free the human slaves that have been captured by the uruk armies and forced to work for sauron, and additional quests to help forge new abilities for talion's sword, bow, and dagger.[5][6][7] the player also has the freedom to pursue side quests and roam around mordor, with special activities to collect specific flora or to hunt certain creatures, or to find old artifacts or elvish seals.[8][9]"

In [50]:
paragraph = re.sub("[^\w\s]|[\d]","",paragraph)
paragraph

'middleearth shadow of mordor is a thirdperson open world actionadventure video game where the player controls a ranger by the name of talion who seeks revenge on the forces of sauron after his family consisting of his wife and son are killed by those that lead them players can travel across locations in the game through parkour riding monsters or accessing forge towers which serve as fast travel points though talion is mortally felled in the games introduction the wraith of the elven lord celebrimbor is able to use his power to keep talion alive along with gifting him wraithlike abilities missions in the game feature main story missions that follow talions quest for revenge side missions that involve following gollum to find artifacts that are tied to celebrimbors past missions to free the human slaves that have been captured by the uruk armies and forced to work for sauron and additional quests to help forge new abilities for talions sword bow and dagger the player also has the freedom to pursue side quests and roam around mordor with special activities to collect specific flora or to hunt certain creatures or to find old artifacts or elvish seals'

In [51]:
doc_spacy = nlp(paragraph)
doc_spacy

middleearth shadow of mordor is a thirdperson open world actionadventure video game where the player controls a ranger by the name of talion who seeks revenge on the forces of sauron after his family consisting of his wife and son are killed by those that lead them players can travel across locations in the game through parkour riding monsters or accessing forge towers which serve as fast travel points though talion is mortally felled in the games introduction the wraith of the elven lord celebrimbor is able to use his power to keep talion alive along with gifting him wraithlike abilities missions in the game feature main story missions that follow talions quest for revenge side missions that involve following gollum to find artifacts that are tied to celebrimbors past missions to free the human slaves that have been captured by the uruk armies and forced to work for sauron and additional quests to help forge new abilities for talions sword bow and dagger the player also has the freedom to pursue side quests and roam around mordor with special activities to collect specific flora or to hunt certain creatures or to find old artifacts or elvish seals

In [53]:
pd_new = pd.DataFrame(columns =["token", "pos_tag"])

for token in doc_spacy:
    pd_new = pd.concat([pd_new, pd.DataFrame.from_records([{"token" : token.text, "pos_tag" : token.pos_}])],ignore_index = True)

pd_new.head(15)

              token pos_tag
0       middleearth   PROPN
1            shadow    NOUN
2                of     ADP
3            mordor   PROPN
4                is     AUX
5                 a     DET
6       thirdperson    NOUN
7              open     ADJ
8             world    NOUN
9   actionadventure   PROPN
10            video    NOUN
11             game    NOUN
12            where   SCONJ
13              the     DET
14           player    NOUN

In [54]:
pd_new_counts = pd_new.groupby(["token", "pos_tag"]).size().reset_index(name = "count").sort_values(by = "count", ascending = False)
pd_new_counts.head(15)

        token pos_tag  count
110       the     DET     12
118        to    PART     10
77         of     ADP      5
109      that    PRON      5
12        and   CCONJ      5
70   missions    NOUN      4
81         or   CCONJ      4
20         by     ADP      3
41        for     ADP      3
59         in     ADP      3
48       game    NOUN      3
56        his    PRON      3
107    talion    NOUN      3
62         is     AUX      3
108   talions    NOUN      2

In [58]:
pd_new_pos = pd_new_counts.groupby("pos_tag")["token"].count().sort_values(ascending = False)
pd_new_pos.head(15)

pos_tag
NOUN     47
VERB     31
ADJ      14
ADP      14
PRON      7
PROPN     6
AUX       5
SCONJ     3
ADV       2
CCONJ     2
DET       2
PART      1
Name: token, dtype: int64