In [7]:
import pandas as pd
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import spacy
from spacy import displacy
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\usama\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [8]:
bbc_news = pd.read_csv('111 - bbc-news.csv')
bbc_news.head()

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...
2,2,7387,Rationing energy is nothing new for off-grid c...,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,Scoraig in the north west Highlands has long h...
3,3,767,The hunt for superyachts of sanctioned Russian...,"Tue, 22 Mar 2022 14:37:01 GMT",https://www.bbc.co.uk/news/60739336,https://www.bbc.co.uk/news/60739336?at_medium=...,"Wealthy Russians sanctioned by the US, EU and ..."
4,4,3712,Platinum Jubilee: 70 years of the Queen in 70 ...,"Wed, 01 Jun 2022 23:17:33 GMT",https://www.bbc.co.uk/news/uk-61660128,https://www.bbc.co.uk/news/uk-61660128?at_medi...,A quick look back at the Queen's 70 years on t...

In [9]:
bbc_news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   object
 3   pubDate      1000 non-null   object
 4   guid         1000 non-null   object
 5   link         1000 non-null   object
 6   description  1000 non-null   object
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [10]:
titles = pd.DataFrame(bbc_news['title'])
titles.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

In [11]:
titles['lowercase'] = titles['title'].str.lower()
titles.head()

,title,lowercase
0,Can I refuse to work?,can i refuse to work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...

In [12]:
en_stopwords = stopwords.words('english')
print(en_stopwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [13]:
titles['stopwords'] = titles['lowercase'].apply(lambda x: ' '.join(word for word in x.split() if word not in en_stopwords))
titles.head()

,title,lowercase,stopwords
0,Can I refuse to work?,can i refuse to work?,refuse work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds

In [14]:
titles['no_punc'] = titles['stopwords'].apply(lambda x: re.sub('[^\w\s]','',x))
titles.head()

,title,lowercase,stopwords,no_punc
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds

In [15]:
titles['token_clean'] = titles['no_punc'].apply(lambda x: word_tokenize(x))
titles.head()

,title,lowercase,stopwords,no_punc,token_clean
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[hunt, superyachts, sanctioned, russian, oliga..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[platinum, jubilee, 70, years, queen, 70, seco..."

In [16]:
titles['token_raw'] = titles['title'].apply(lambda x: word_tokenize(x))
titles.head()

,title,lowercase,stopwords,no_punc,token_clean,token_raw
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[refuse, work]","[Can, I, refuse, to, work, ?]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"[liz, truss, brief, world, reacts, uk, politic...","['Liz, Truss, the, Brief, ?, ', World, reacts,..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[rationing, energy, nothing, new, offgrid, com...","[Rationing, energy, is, nothing, new, for, off..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[hunt, superyachts, sanctioned, russian, oliga...","[The, hunt, for, superyachts, of, sanctioned, ..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[platinum, jubilee, 70, years, queen, 70, seco...","[Platinum, Jubilee, :, 70, years, of, the, Que..."

In [17]:
lemmatizer = WordNetLemmatizer()
titles["token_clean_lemmatize"] = titles["token_clean"].apply(lambda x: [lemmatizer.lemmatize(token) for token in x])
titles.head()

,title,lowercase,stopwords,no_punc,token_clean,token_raw,token_clean_lemmatize
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[refuse, work]","[Can, I, refuse, to, work, ?]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"[liz, truss, brief, world, reacts, uk, politic...","['Liz, Truss, the, Brief, ?, ', World, reacts,...","[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[rationing, energy, nothing, new, offgrid, com...","[Rationing, energy, is, nothing, new, for, off...","[rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[hunt, superyachts, sanctioned, russian, oliga...","[The, hunt, for, superyachts, of, sanctioned, ...","[hunt, superyachts, sanctioned, russian, oliga..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[platinum, jubilee, 70, years, queen, 70, seco...","[Platinum, Jubilee, :, 70, years, of, the, Que...","[platinum, jubilee, 70, year, queen, 70, second]"

In [18]:
list_raw = sum(titles["token_raw"],[])
list_clean = sum(titles["token_clean_lemmatize"],[])

In [19]:
nlp = spacy.load("en_core_web_sm")

In [20]:
spacy_doc_clean = nlp(' '.join(list_clean))
spacy_doc_clean

refuse work liz truss brief world reacts uk political turmoil rationing energy nothing new offgrid community hunt superyachts sanctioned russian oligarch platinum jubilee 70 year queen 70 second red bull found guilty breaking formula 1 budget cap world triathlon championship series flora duffy beat georgia taylorbrown womens title terry hall coventry scooter rideout pay tribute singer post office fujitsu face inquiry horizon scandal pavement parking frightens me uk interest rate rise affect high could go stayed storm happens now six nation scotland best since 99 beat best ireland ever long liz truss survive prime minister platinum jubilee beacon light across globe celebrate queen reign top student loan interest rate cut 5 england russian said theyd take baby medic story week picture 1117 june 2022 xi jinping hong kong tight security city mark 25 year handover rescue carried silence listen sound life nick pope newcastle goalkeeper extends incredible clean sheet record china plan become next big space power barcelona thrash leader real madrid famous clasico win kuenssberg budget can not mask big change economy nicola bulley search know disappearance cost living christmas light display survive energy crisis 100yearold edinburgh man still working three day week freya 600kg walrus cause stir norway offer uk home ukrainian refugee nicola bulley search former police bos say criticism unfair bolduc democrat elevated republican backfire strike action cancelled queen death neighbourhood leading green energy revolution men u17 european championship dutch 17yearold isaac babadi score panenka penalty amtrak derailment three killed missouri train hit truck energy price cap rising bill four discount payment could help environment mushroom board future surfing flying boat tech cleaner shipping scottish football ban heading day match chris eubank jr v liam smith next boxing unacceptable taunt town destroyed make way whitesonly suburb ukraine war village celebrates russian retreat root hit ton england take command west indie heineken champion cup leicester 166 edinburgh jasper wiese try sends tiger last eight world cup 2022 bellingham gakpo fernandez breakout star briton jack fenton killed greek helicopter accident emotional sue barker get centre court ovation ukrainian skating sister back doing love england v india edgbaston official investigate crowd racism test newspaper headline rwanda plan will fail sa train kyiv force name leon sir lenny henry brings moving adoption story screen big brother star glyn wise plan priest minister asleep wheel dentist shortage say lib dems chris kaba met suspends officer shot dead unarmed man world cup 2022 learned group stage saw record number upset james webb nasa space telescope delivers spectacular picture constitution hill cheltenham champion hurdle winner the horse generation least one victim could survived arena bomb inquiry gareth bale wale captain retires football aged 33 ukraine war silent street wiped donetsk town world cup 2022 vittorio pozzos legacy record might finally threat train strike worker vote six month walkout eidevall 100 sure arsenal advance firstleg draw ukraine war returning place father killed furniture firm made collapse customer dark refund widow u capitol riot officer stigma death nh reach deal lifesaving breastcancer drug giant ceramic sculpture sandy brown unveiled cornwall ceo secret one company attracts men boris becker tennis superstar crashed earth turkish mine explosion kill 25 leaf dozen trapped indian well andy murray emma raducanu jack draper win reach third round world athletics championship gb keely hodgkinson narrowly miss gold dramatic 800m nh crisis medic trying fix health service jet crash block flat russia prince harry meghan get money chelsea 42 man utd chelsea win historic third successive wsl title tory leadership rather lose right thing say sunak omagh police shooting four men released john caldwell attack northern ireland 10 italy sarah mcfadden score famous winner belfast actress clara darcy starring play brain tumour bridgerton south asian face tv make happy prince harry remembers queen elizabeth ii infectious smile million receive latest costofliving payment joe biden head middle east amid faltering u sway nh public satisfaction health service drop record low seen major winter storm paper lion bare teeth starmers migration policy afghanistan pupil fear spate islamic state attack princess wale kate pay tribute queen elizabeth carol service emma raducanu u open champion discusses tough split coach torben beltz oxford united 03 arsenal eddie nketiah score twice gunner progress ukraine roundup putin defends necessary invasion kyiv averts cyberattack ni protocol uk eu reach agreement trade data sharing super mario bros movie jack black rise game adaptation fourtime slam champion osaka announces pregnancy mcdonalds cocacola boycott call grow russia womens footballer year contender sam kerr war ukraine vladimir putin trained fighter africa ryanairs michael oleary want practical immigration approach i planned end life 16 still here england 14 men whipped twickenham crowd stirring display open rory mcilroy viktor hovland share lead st andrew third round real madrid 20 eintracht frankfurt karim benzema score 324th goal real super cup win paper boris dossier judge to back down rwanda queen pull attending commonwealth service mosque fire suspect arrested second attack world cup 2022 belgium drop love away shirt qatar uk living covid plan soho street turned new london art gallery paper cruise ship house migrant new nh cash pay gap boss staff widen think tank local election child urge action save wildlife climate change uk track meet target trump investigation empty folder marked classified found maralago jim ratcliffe man bidding man utd shropshire baby death parent whose life changed forever bus journey taken since 2 fare cap say watchdog mexico kidnapping twisted moral code explains cartel apology rail fare england rise inflation rate minister say taliban school uturn a devastating day afghan girl malala yousafzai met police next force casey review ukraine war kherson mariupol key russian success heineken champion cup premiership cap hinders english team alex sanderson ukraine war protester expose crack kremlin war message liz truss vow match ukraine military support politics return wale population hit new high growth lowest many ukrainian fled home gone deloitte report european football made significant recovery covid pandemic nigeria flood overwhelming disaster leaf 600 people dead wimbledon emma raducanu andy murray set centre court day one journey site nord stream explosion quiz week lindsay lohan trouble gracie spinks receipt could traced killer family supreme court happens roe v wade overturned chancellor warns tax rise squeeze spending imran khan ousted pakistan pm key vote artemis nasa orion capsule break distance record ukraine winning social medium war flint arrest missing girl 12 found birmingham france drought parched town left short drinking water invergordon shed door marble bust could sold massive toll living leasehold property ukraine war put value profit nato chief tell country buyer revive interest city flat return office uk weather long cold snap last hidilyn diaz accusation antigovernment plot historic olympic gold government introduce independent football regulator england backing fanled review pint power parent three way budget could affect alevel gcse exam happens paper nato nordic expansion threat boost europe sudden unknown death childhood why beautiful son die droylsden man charged girl 6 abducted sexually assaulted fa cup wrexham 33 sheffield united egans late strike denies wrexham victory uk compassionate say pm suella braverman invasion row foreign secretary liz truss join tory leadership race world cup 2022 wale must put big boy pant on england say bos robert page forgive man tried murder announces leader death name replacement nurse strike much know pay try quiz rishi sunak speaks safety fear daughter leslie jordan grace star dy aged 67 olivia prattkorbel murderaccused highlevel drug dealer north carolina suspect15 custody raleigh shooting spree uk weather long cold snap last queen funeral guest attend rishi sunaks failure wear seat belt investigated heathrow airport extends cap passenger end october john peel family selling rare item archive mp call uk ban two chinese cctv firm u economy shrink sparking recession fear womens t20 world cup england india prepare decisive group stage encounter michaela mcareavey two men apologise video mocking bride murder scotland 21 republic ireland ryan christie late penalty give host crucial win much could mortgage rise try calculator covid vaccine linked death major u study find oscar 2023 rrrs naatu naatu win best original song paper russia accused genocide fuel duty cut forest set new record transferwindow rush watch russian tank abandoned retaken ukrainian territory could elgin marble returned greece review nottingham nh maternity failing launch world cup 2022 fan miss kickoff fifa ticket app issue england u21s 30 albania u21s young lion qualify 2023 european under21 championship make movie without huge carbon footprint tv presenter matthew bassett show life go spinal injury gta rockstar rejected eminem movie deal say insider world cup 2022 france kylian mbappe upstage olivier giroud goalscoring record mystery death two saudi sister sydney matt hancock celebrity led dozen complaint mp watchdog cricket world cup englandaustralia final shown free air sunday nurse strike thousand join first walkout sad day exeter man held murder woman ludwell valley park tory leadership truss criticised macron jury out remark keir starmer right wage stuck decade were behind you famous face cheer lioness zelensky asked give russia part ukraine amber heard easy forget human worker take london street amid cost living crisis my cancerous tumour big kettle bell chester zoo rare baby wallaby emerges mother pouch world cup 2022 belgium afraid lose morocco say roberto martinez boy george tear hancock enters celeb camp elon musk defends racist tirade dilbert creator scott adam henry cat heart addenbrookes hospital week picture 2 8 april 2022 former uk pm boris johnson make trip ukraine picture sporting memory queen cody gakpo liverpool agree sign forward say psv eindhoven prince william oversees trooping colour rehearsal new reality woman seeking abortion texas water pipe robot could stop billion litre leaking london west end man crushed telescopic urinal dy emma raducanu injured british number one face race fit wimbledon world cup south korea reach last 16 dramatic lastgasp win portugal china spy balloon u navy release photo debris child q schoolgirl stripsearch isolated issue police data suggests everybody allowed play football liverpool 33 brighton jurgen klopp vow red fight difficult spell rugby world cup england claudia macdonald hannah botterman start commonwealth game andrea spendolinisirieix noah williams win mixed synchronised 10m platform gold suella braverman challenge critic oust asylum row beth mead arsenal forward say record wsl crowd still beginning manchester united 30 sheriff tiraspol cristiano ronaldo score comfortable win t20 world cup england v india semifinal jos buttler alex hale star orkney part scallop disco fishing trial putin mariupol russian president saw visit ukraine war jewish child airlifted israel politics increasingly dealbreaker u dating scene covid19 china shanghai getting used new normal vietnam veteran win lottery six time intuition council tax much rising alex murdaugh trial power privilege murder downfall dynasty leicester city bos brendan rodgers vow to fight on survive edgware man arrested woman dy christmas day crash sweden 50 portugal man city filippa angeldal score two easy win swede ukraine war russian foreign minister sergei lavrov factchecked dominic raab face question aggressive behaviour claim pakistan flood map beforeafter photo show extent devastation sri lanka protest unifying nation ethnic fault line run deep u dollar strong mean disabled shropshire man completes sevenday marathon feat charlotszyu undisputed world champion break hand leila borrington woman jailed killing threeyearold stepson fa cup 2023 highlight joao palhinha manor solomon score wonder goal fulham beat leeds united alabama hunt missing prison inmate guard billie jean king cup final great britain underdog inspired glasgow past experience liverpool bos jurgen klopp say planning fa cup semifinal ridiculous mariupol video appear show dead civilian u open rory mcilroy england callum tarren one behind leader adam hadwin ml launch investigation dc united forward taxi fountas accused using racial slur match day 2 analysis bruno guimaraes game newcastle reanne evans beat stuart bingham become first woman win match snooker shoot ukraine conflict growing number firm pull back russia oleksiy vadatursky ukraine grain tycoon killed russian shelling mykolaiv tory member vent fury rishi sunaks coronation mp antonio conte italian thanks tottenham fan sharing passion football watch drama 60 second corrie mckeague would bingedrink friend death inquest british gymnastics name banned coach zero tolerance plan abuse strike rule trade union allowed strike commonwealth game england woman beat australia win historic first hockey gold worrying number slim child dieting wallasey pub shooting woman fatally shot targeted police putin set midnight deadline rouble gas payment big zuu breaking mould cookery show wayne quilliam photographing diversity aboriginal australia tory mp express concern tax cut pound fall war ukraine factchecking russian claim nato troop fighting ukraine ni election 2022 prime minister visit ni dup block assembly court bid protect tenant renttorent ghost landlord hundred boundary womens competition small duhan van der merwe score sensational six nation try scotland beat england rrr indian action spectacle charming west john lennon son open yoko ono performance centre liverpool background smith attack omagh police attack john caldwell ha suffered lifechanging injury pelosi visit taiwan put ball firmly xi jinpings court eva kaili senior eu lawmaker arrested alleged bribery gulf state england v south africa sophia dunkley ton lead host convincing win second odi doctor raise safety fear birmingham hospital energy saving scheme energy saving scheme electricity commonwealth game australia beat india nine run claim cricket gold man utd 21 liverpool ten hag get big call right manchester united stun liverpool historic english pub recognised interior pope francis apologises indigenous people canada swingometer inventor sir david butler dy 98 met police dark corner force wayne couzens worked ukraine war boris johnson visit sweden finland mountaineer jp mohrs message we reach summit deal ataglance house zana owner hope zara trademark win inspire others face face bandit warlord nigeria bucha murder german report say russian troop discussed killing bruce lehrmann australia parliament rape retrial abandoned love island ekinsu davide crowned 2022 winner live final england v south africa issy wong take late wicket boost host nba warrior coach texas school shooting when going something mary queen scot deposed ruler secret prison letter found decoded ukraine war im scared new teacher war big uk trial find best drug fight flu area new record july heatwave uk covid inquiry draft term reference set mp pierce johnson armour big moment durban flood survivor i thought world ending amazon begin drone delivery lockeford california year petrol price fuel duty going up michelle donelan new education secretary facing thousand complain hmrc tax repayment twitch streamer kai cenat break subscriber record champion league nearly 2000 liverpool fan set sue uefa climate change force indigenous islander panama relocate cost living firm warned consumer want low price kenya investigate sex work exposed bbc tea documentary wizz air suspend moldova flight airspace safety bristol mayor fly nine hour ted climate conference victoria azarenka want safeguarding improved female player being spiked stopped going again royal mail overseas parcel ban costing hundred pound doctor trailer drop fan christmas ae absolute chaos spent 15 hour trolley paper voter cost living fear drought day away ukraine yarmolenko get europa winner west ham england v south africa ben stokes change approach despite firsttest loss french open coco gauff call peace end gun violence camera message indonesia 120 dead football stampede excess death 2022 among worst 50 year it bit weird young mormon missionary bootcamp training italy world cup azzurri turn disaster north macedonia better future petr pavel exgeneral beat populist rival czech election half million people watch study tiktok comedian rhod gilbert receiving treatment cancer quiz week cristiano ronaldos offfield goal deptford london high street voted one world coolest alzheimers neil kinnock supporting wife disease paper wake zombie truss softens handout rock really power light bulb no say expert mind game argentina dancing hero olivier 2022 jason manfords best joke 7 highlight author benjamin myers cropcircle maker blew people mind king coronation oil animalcruelty free truss tax cut clearly wrong approach say shapps missing doncaster cockatiel prompt unusual search tactic owner election result 2022 boris johnson admits tough loss tory uk election 2022 really simple guide almost 400 migrant cross channel small boat grenfell tragedy government failing act inquiry report say london mayor josephine tewson keeping appearance actress dy 91 margaret thatcher secret brahms phone invented texas shooting sunny uvalde school day ended bloodshed hay fever getting worse uk ukraine war map tracking russian invasion covid spring booster jab launch over75s high risk england u midterm election finland answer fake news edinburgh festival biggest art festival world begin world cup 2022 wale allen back bale ramsey shine england game crown new season watched 11m uk launch day first official rating say partygate downing street party resulted fine far ukraine war rishi sunak visit president zelensky kyiv pledge 50m aid u tracking suspected chinese surveillance balloon cost living we work cant afford family rent assad syria leader make historic visit uae peru protest machu picchu closed indefinitely tourist stranded it felt like u looked like u klopp hail derby win macron defeat le pen vow unite divided france losing wife pancreatic cancer taught life loss world cup 2022 travelling fan found qatar tournament tree gift thousand u city world aquatic championship summer mcintosh 15 win gold great britain take relay bronze happened uk economy pound mortgage week traitor viewer became loyal bbc reality series picture harry meghan join royal national service thanksgiving euro 2022 look quarterfinal worcester warrior owner agree term sale club interested party chocolate sweet price jump ahead easter record number nurse quitting nh wimbledon ban russian player discrimination andrey rublev steve barclay new health secretary tackle first elaine thompsonherah beat dina ashersmith emphatic diamond league win labour conference sir keir starmer back net zero electricity boost growth sunak tried every way worked queen elizabeth ii personal touch plan funeral day european under19 championship england 40 serbia highlight washington dc tipping point migrant arrive border flesheating bug swansea dj tell graze almost killed vanessa bryant testifies blindsided leaked photo match peace tour i friend ukraine gun now cost living tip cut energy heating cost home photographer pick top shot year biden say maga force threaten u democracy roman abramovich chelsea credit card facility temporarily suspended megafire rip swathe land near bordeaux bristol mum writes heart surgery book help son jeremy corbyn starmer move flagrant attack democracy ukraine war oligarch euge

In [21]:
pos_bbc = pd.DataFrame(columns = ["token", "pos"])

for word in spacy_doc_clean:
    pos_bbc = pd.concat([pos_bbc,pd.DataFrame.from_records([{"token" : word.text, "pos" : word.pos_}])],ignore_index =True)

pos_bbc.head()

    token    pos
0  refuse    AUX
1    work   NOUN
2     liz  PROPN
3   truss    ADJ
4   brief    ADJ

In [22]:
pos_bbc_count = pos_bbc.groupby(["token","pos"]).size().reset_index( name = "count").sort_values(by = "count", ascending = False)
pos_bbc_count.head()

        token    pos  count
30       2022    NUM     47
1162  england  PROPN     45
870       cup  PROPN     39
3056      say   VERB     37
3707       uk  PROPN     37

In [23]:
pos_bbc_noun = pos_bbc_count[pos_bbc_count.pos == "NOUN"][0:10]
pos_bbc_noun

       token   pos  count
3840     war  NOUN     34
3948   world  NOUN     30
2136     man  NOUN     22
907      day  NOUN     21
3973    year  NOUN     20
1158  energy  NOUN     17
2847  record  NOUN     17
2657  police  NOUN     16
3870    week  NOUN     16
3935   woman  NOUN     16

In [24]:
pos_bbc_verb = pos_bbc_count[pos_bbc_count.pos == "VERB"][0:10]
pos_bbc_verb

        token   pos  count
3056      say  VERB     37
3711  ukraine  VERB     22
1380    found  VERB     13
3461     take  VERB     13
1651      hit  VERB     13
358      beat  VERB     13
2133     make  VERB     13
1459      get  VERB     13
1473     give  VERB     11
3918      win  VERB     10

In [25]:
spacy_doc = nlp(' '.join(list_raw))
spacy_doc

Can I refuse to work ? 'Liz Truss the Brief ? ' World reacts to UK political turmoil Rationing energy is nothing new for off-grid community The hunt for superyachts of sanctioned Russian oligarchs Platinum Jubilee : 70 years of the Queen in 70 seconds Red Bull found guilty of breaking Formula 1 's budget cap World Triathlon Championship Series : Flora Duffy beats Georgia Taylor-Brown to women 's title Terry Hall : Coventry scooter ride-out pays tribute to singer Post Office and Fujitsu to face inquiry over Horizon scandal 'Pavement parking frightens me ' UK interest rates : How will the rise affect you and how high could it go ? They stayed for the storm - what happens now ? Six Nations : Can Scotland 's best since '99 beat best Ireland ever ? How long can Liz Truss survive as prime minister ? Platinum Jubilee : Beacons light across the globe to celebrate Queen 's reign Top student loan interest rate cut by 5 % in England Russians said they ’ d take my baby : A medic ’ s story Week in pictures : 11-17 June 2022 Xi Jinping in Hong Kong : Tight security as city marks 25 years of handover Rescues carried out in silence to listen for sounds of life Nick Pope : Newcastle goalkeeper extends incredible clean sheet record How China plans to become the next big space power Barcelona thrash leaders Real Madrid in famous Clasico win Kuenssberg : The Budget can not mask big changes to our economy Nicola Bulley search : What we know about her disappearance Cost of living : Can Christmas lights displays survive the energy crisis ? The 100-year-old Edinburgh man still working three days a week Freya the 600kg walrus causes a stir in Norway How can I offer a UK home to Ukrainian refugees ? Nicola Bulley search : Former police boss says criticism is unfair Don Bolduc : Democrats elevated this Republican . Will it backfire ? Some strike action cancelled after the Queen 's death The neighbourhood leading a green energy revolution Men 's U17 European Championship : Dutch 17-year-old Isaac Babadi scores Panenka penalty Amtrak derailment : Three killed in Missouri after train hits truck Energy price cap : Rising bills - four discounts and payments that could help you Environment : Are mushroom boards the future of surfing ? Flying boats and other tech for cleaner shipping Scottish football to ban heading the day before and after matches Chris Eubank Jr v Liam Smith : What next for boxing after 'unacceptable ' taunts ? The town destroyed to make way for a whites-only suburb Ukraine war : A village celebrates Russian retreat Root hits ton as England take command against West Indies Heineken Champions Cup : Leicester 16-6 Edinburgh - Jasper Wiese try sends Tigers into last eight World Cup 2022 : Bellingham , Gakpo , Fernandez and other breakout stars Briton Jack Fenton killed in Greek helicopter accident Emotional Sue Barker gets Centre Court ovation Ukrainian skating sisters back to 'doing what they love ' England v India : Edgbaston officials investigate crowd racism at Test Newspaper headlines : Rwanda plan 'will fail ' and 'SAS train Kyiv forces ' My Name Is Leon : Sir Lenny Henry brings 'moving ' adoption story to screen Big Brother star Glyn Wise plans to be priest Ministers asleep at the wheel over dentist shortages , say Lib Dems Chris Kaba : Met suspends officer who shot dead unarmed man World Cup 2022 : What we learned from a group stage that saw record number of upsets James Webb : Nasa space telescope delivers spectacular pictures Constitution Hill : Cheltenham Champion Hurdle winner 'the horse of a generation ' At least one victim could have survived arena bomb - inquiry Gareth Bale : Wales captain retires from football aged 33 Ukraine war : Silent streets in wiped out Donetsk town World Cup 2022 : Vittorio Pozzo 's legacy and a record that might finally be under threat Train strikes : Workers vote on further six months of walkouts Eidevall '100 % sure ' Arsenal will advance after first-leg draw Ukraine war : Returning to the place my father was killed Furniture firm Made collapse : Customers in the dark over refunds Widow of US Capitol riot officer on 'stigma ' of his death NHS reaches deal for life-saving breast-cancer drug Giant ceramic sculpture by Sandy Brown has been unveiled in Cornwall CEO Secrets : How one company attracts more men Boris Becker : How a tennis superstar crashed to earth Turkish mine explosion kills 25 and leaves dozens trapped Indian Wells : Andy Murray , Emma Raducanu and Jack Draper win to reach third round World Athletics Championships : GB 's Keely Hodgkinson narrowly misses out on gold in dramatic 800m NHS crisis : The medics trying to fix the health service How did jet crash into a block of flats in Russia ? Prince Harry and Meghan : Where do they get their money ? Chelsea 4-2 Man Utd : Chelsea win historic third successive WSL title Tory leadership : I 'd rather lose doing right thing , says Sunak Omagh police shooting : Four men released over John Caldwell attack Northern Ireland 1-0 Italy : Sarah McFadden scores famous winner in Belfast Actress Clara Darcy : Why I 'm starring in a play about my brain tumour Bridgerton : South Asian faces on TV 'makes me happy ' Prince Harry remembers Queen Elizabeth II 's infectious smile Millions to receive latest cost-of-living payment Joe Biden heads to Middle East amid faltering US sway NHS : Public satisfaction with health service drops to record low Why have n't we seen any major winter storms ? The Papers : Lions 'bare teeth ' and Starmer 's migration policy Afghanistan pupils in fear after spate of Islamic State attacks Princess of Wales Kate pays tribute to Queen Elizabeth at carol service Emma Raducanu : US Open champion discusses 'tough ' split with coach Torben Beltz Oxford United 0-3 Arsenal : Eddie Nketiah scores twice as Gunners progress Ukraine round-up : Putin defends 'necessary ' invasion and Kyiv averts cyber-attack NI Protocol : UK and EU reach agreement on trade data sharing Super Mario Bros. movie : Jack Black on the rise of game adaptations Four-time Slam champion Osaka announces pregnancy McDonald 's and Coca-Cola boycott calls grow over Russia Women 's Footballer of the Year contender Sam Kerr War in Ukraine : Why Vladimir Putin could n't have trained fighters in Africa Ryanair 's Michael O'Leary wants 'practical ' immigration approach ' I planned to end my life at 16 but I 'm still here ' How England 's 14 men whipped up Twickenham crowd with stirring display The Open : Rory McIlroy and Viktor Hovland share lead at St Andrews after third round Real Madrid 2-0 Eintracht Frankfurt : Karim Benzema scores 324th goal for Real in Super Cup win The Papers : Boris dossier and judges 'to back down ' on Rwanda Queen pulls out of attending Commonwealth Service Mosque fire suspect arrested over second attack World Cup 2022 : Belgium to drop 'love ' from away shirts in Qatar What are the UK 's Living with Covid plans ? Soho 's streets turned into new London art gallery The Papers : 'Cruise ships ' to house migrants and new NHS cash Pay gap from bosses to staff to widen - think tank Local elections : Children urge action to save wildlife Climate change : Is the UK on track to meet its targets ? Trump investigation : Empty folders marked classified found at Mar-a-Lago Jim Ratcliffe : Who is the man bidding for Man Utd ? Shropshire baby deaths : The parents whose lives were changed forever More bus journeys taken since £2 fare cap , says watchdog Mexico kidnapping : A twisted moral code explains cartel 's apology Rail fares in England to rise below inflation rate , ministers say Taliban schools U-turn ' a devastating day ' for Afghan girls - Malala Yousafzai Met Police : Where next for the force after Casey review ? Ukraine war : Why Kherson and Mariupol are key to Russian success Heineken Champions Cup : Premiership cap hinders English teams - Alex Sanderson Ukraine war : Protester exposes cracks in Kremlin 's war message Liz Truss vows to match Ukraine military support as politics returns Wales ' population hits new high but growth is lowest How many Ukrainians have fled their homes and where have they gone ? Deloitte report : European football has made 'significant recovery ' after Covid pandemic Nigeria floods : 'Overwhelming ' disaster leaves more than 600 people dead Wimbledon : Emma Raducanu & Andy Murray set for Centre Court on day one A journey to the site of the Nord Stream explosions Quiz of the week : Why was Lindsay Lohan in trouble ? Gracie Spinks : Receipt could have traced killer - family Supreme Court : What happens if Roe v Wade overturned ? Chancellor warns of tax rises and squeeze on spending Imran Khan ousted as Pakistan 's PM after key vote Artemis : Nasa 's Orion capsule breaks distance record How Ukraine is winning the social media war Flint : Arrest as missing girl , 12 , found in Birmingham France drought : Parched towns left short of drinking water Invergordon shed door marble bust could be sold 'Massive toll ' of living in a leasehold property Ukraine war : Put values over profits , Nato chief tells countries Buyers revive interest in city flats after return to office UK weather : How long will the cold snap last ? Hidilyn Diaz : From accusations of anti-government plot to historic Olympic gold Government to introduce independent football regulator in England after backing fan-led review Pints , power and parents : Three ways the Budget could affect you A-level and GCSE exams : What happens to your papers ? Is Nato 's Nordic expansion a threat or boost to Europe ? Sudden unknown death in childhood : 'Why did my beautiful son die ? ' Droylsden : Man charged after girl , 6 , abducted and sexually assaulted FA Cup : Wrexham 3-3 Sheffield United - Egan 's late strike denies Wrexham victory UK is compassionate , says PM after Suella Braverman invasion row Foreign Secretary Liz Truss joins Tory leadership race World Cup 2022 : Wales must 'put big boy pants on ' against England , says boss Robert Page I forgive the man who tried to murder me IS announces leader 's death and names replacement Nurses ' strike : How much do you know about their pay ? Try our quiz Rishi Sunak speaks of safety fears for daughter Leslie Jordan : Will and Grace star dies aged 67 Olivia Pratt-Korbel murder-accused was 'high-level ' drug dealer North Carolina : Suspect,15 , in custody after Raleigh shooting spree UK weather : How long will the cold snap last ? Queen 's funeral guests : Who will - and who wo n't - attend Rishi Sunak 's failure to wear seat belt to be investigated Heathrow Airport extends cap on passengers to end of October John Peel 's family selling rare items from his archive MPs call for UK ban on two Chinese CCTV firms US economy shrinks again sparking recession fears Women 's T20 World Cup : England and India prepare for decisive group stage encounter Michaela McAreavey : Two men apologise for video mocking bride 's murder Scotland 2-1 Republic of Ireland : Ryan Christie 's late penalty gives hosts crucial win How much could your mortgage rise ? Try our calculator Covid vaccines not linked to deaths , major US study finds Oscars 2023 : RRR 's Naatu Naatu wins best original song The Papers : Russia accused of genocide , and 'fuel duty cut ' Forest set new record after transfer-window rush WATCH : Russian tanks abandoned on retaken Ukrainian territory Could the Elgin Marbles be returned to Greece ? Review into Nottingham NHS maternity failings launches World Cup 2022 : Some fans miss kick-off after Fifa ticket app issues England U21s 3-0 Albania U21s : Young Lions qualify for 2023 European Under-21 Championship How to make movies without a huge carbon footprint TV presenter Matthew Bassett shows life goes on with spinal injury GTA : Rockstar rejected Eminem movie deal , says insider World Cup 2022 : France 's Kylian Mbappe upstages Olivier Giroud after goalscoring record The mystery deaths of two Saudi sisters in Sydney Matt Hancock on I 'm A Celebrity led to dozens of complaints to MPs ' watchdog Cricket World Cup : England-Australia final to be shown free to air on Sunday Nurses strike : Thousands join first walkout on 'sad day ' Exeter : Man held over murder of woman in Ludwell Valley Park Tory leadership : Truss criticised for Macron 'jury is out ' remark Is Keir Starmer right that wages have been 'stuck for a decade ' ? 'We 're all behind you ' : Famous faces cheer Lionesses Zelensky asked if he 'll give Russia any part of Ukraine Amber Heard : It 's easy to forget I 'm a human being Workers take to London 's streets amid cost of living crisis 'My cancerous tumour was as big as a kettle bell ' Chester Zoo : Rare baby wallaby emerges from mother 's pouch World Cup 2022 : Belgium were 'afraid to lose ' against Morocco , says Roberto Martinez Boy George 's tears as Hancock enters I 'm a Celeb camp Elon Musk defends racist tirade by Dilbert creator Scott Adams How Henry the cat won the hearts of Addenbrooke 's Hospital Week in pictures : 2 - 8 April 2022 Former UK PM Boris Johnson makes trip to Ukraine In pictures : Sporting memories of the Queen Cody Gakpo : Liverpool agree to sign forward , say PSV Eindhoven Prince William oversees Trooping the Colour rehearsal A new reality for women seeking an abortion in Texas Water pipe robots could stop billions of litres leaking London 's West End : Man crushed by telescopic urinal dies Emma Raducanu : Injured British number one faces race to be fit for Wimbledon World Cup : South Korea reach last 16 with dramatic last-gasp win over Portugal China spy balloon : US Navy releases photos of debris Child Q : Schoolgirl strip-search not isolated issue , police data suggests 'Everybody should be allowed to play football ' Liverpool 3-3 Brighton : Jurgen Klopp vows Reds will fight through difficult spell Rugby World Cup : England 's Claudia MacDonald and Hannah Botterman start Commonwealth Games : Andrea Spendolini-Sirieix & Noah Williams win mixed synchronised 10m platform gold Suella Braverman challenges critics to oust her in asylum row Beth Mead : Arsenal forward says record WSL crowd is 'still just the beginning ' Manchester United 3-0 Sheriff Tiraspol : Cristiano Ronaldo scores in comfortable win T20 World Cup - England v India semi-final : Jos Buttler & Alex Hales star Orkney part of 'scallop discos ' fishing trial Putin in Mariupol : What the Russian president saw on his visit Ukraine war : Jewish children airlifted to Israel Politics increasingly a deal-breaker on US dating scene Covid-19 in China : Shanghai getting used to 'new normal ' Vietnam veteran wins lottery six times on intuition Council tax : What is it and how much is it rising ? Alex Murdaugh trial : Power , privilege , murder and the downfall of a dynasty Leicester City boss Brendan Rodgers vows 'to fight on ' - but can he survive ? Edgware : Man arrested after woman dies in Christmas Day crash Sweden 5-0 Portugal : Man City 's Filippa Angeldal scores two in easy win for Swedes Ukraine War : Russian Foreign Minister Sergei Lavrov fact-checked Dominic Raab faces questions over aggressive behaviour claims Pakistan floods : Map and before/after photos show extent of devastation Sri Lanka : The protests unifying a nation where ethnic fault lines run deep Why is the US dollar so strong , and what does it mean ? Disabled Shropshire man completes seven-day marathon feat Charlo-Tszyu off as undisputed world champion breaks hand Leila Borrington : Woman jailed for killing three-year-old stepson FA Cup 2023 highlights : Joao Palhinha and Manor Solomon score wonder goals as Fulham beat Leeds United Alabama hunt for missing prison inmate and guard Billie Jean King Cup Finals : Great Britain 's 'underdogs ' inspired in Glasgow by past experience Liverpool boss Jurgen Klopp says planning for FA Cup semi-final 'ridiculous ' Mariupol : Videos appear to show dead civilians US Open : Rory McIlroy and England 's Callum Tarren one behind leader Adam Hadwin MLS launches investigation after DC United forward Taxi Fountas accused of using racial slur Match of the Day 2 analysis : How Bruno Guimaraes won the game for Newcastle Reanne Evans beats Stuart Bingham to become first woman to win a match at Snooker Shoot Out Ukraine conflict : Growing numbers of firms pull back from Russia Oleksiy Vadatursky : Ukraine grain tycoon killed in Russian shelling of Mykolaiv Tory members vent fury at Rishi Sunak ’ s coronation by MPs Antonio Conte : Italian thanks Tottenham and fans for sharing 'passion ' for football Watch all the drama in 60 seconds Corrie Mckeague would binge-drink after friend 's death - inquest British Gymnastics to name banned coaches in 'zero tolerance ' plan on abuse Strike rules : What is a trade union and who is allowed to strike ? Commonwealth Games : England 's women beat Australia to win historic first hockey gold Worrying number of slim children dieting Wallasey pub shooting : Woman fatally shot was not targeted - police Putin sets midnight deadline over rouble gas payments Big Zuu on breaking the mould for cookery shows Wayne Quilliam : Photographing the diversity of Aboriginal Australia Tory MPs express concern over tax cuts as pound falls War in Ukraine : Fact-checking Russian claims that Nato troops are fighting in Ukraine NI Election 2022 : Prime minister to visit NI as DUP blocks assembly Court bid to protect tenants from rent-to-rent ‘ ghost landlords ’ The Hundred : Are the boundaries in the women 's competition too small ? Duhan van der Merwe scores sensational Six Nations try as Scotland beat England RRR : Why the Indian action spectacle is charming the West John Lennon 's son opens Yoko Ono performance centre in Liverpool What is the background to Will Smith 's attack ? Omagh police attack : John Caldwell 'has suffered life-changing injuries ' Pelosi visit : Taiwan puts the ball firmly in Xi Jinping 's court Eva Kaili : Senior EU lawmaker arrested over alleged bribery by Gulf state England v South Africa : Sophia Dunkley ton leads hosts to convincing win in second ODI Doctors raise safety fears at Birmingham hospitals Energy saving scheme : What is the energy saving scheme for electricity ? Commonwealth Games : Australia beat India by nine runs to claim cricket gold Man Utd 2-1 Liverpool : Ten Hag gets big calls right as Manchester United stun Liverpool Historic English pubs recognised for their interiors Pope Francis apologises to indigenous people of Canada Swingometer inventor Sir David Butler dies at 98 Met Police : The 'dark corner ' of the force where Wayne Couzens worked Ukraine war : Boris Johnson visits Sweden and Finland Mountaineer JP Mohr 's message : `` We can all reach our summits '' The deal at-a-glance House of Zana owner hopes Zara trademark win will inspire others Face to face with the bandit warlords of Nigeria Bucha murders : German report says Russian troops discussed killings Bruce Lehrmann : Australia parliament rape retrial abandoned Love Island : Ekin-Su and Davide crowned 2022 winners in live final England v South Africa : Issy Wong takes late wickets to boost hosts NBA Warriors coach on Texas school shooting : 'When are we going to do something ? ' Mary Queen of Scots : Deposed ruler 's secret prison letters found and decoded Ukraine war : ' I 'm more scared of my new teacher than of war ' Big UK trial to find best drugs to fight flu Did your area have a new record during the July heatwave ? UK Covid inquiry draft terms of reference set out Did MPs pierce Johnson 's armour ? The big moments Durban floods survivors : ' I thought the world was ending ' Amazon to begin drone deliveries in Lockeford , California this year Petrol prices : What is fuel duty and is it going up ? Who is Michelle Donelan and what is the new education secretary facing ? Thousands complain to HMRC about tax repayments Twitch streamer Kai Cenat breaks subscriber record Champions League : Nearly 2,000 Liverpool fans set to sue Uefa Climate change forces indigenous islanders in Panama to relocate Cost of living : Firms warned c

In [26]:
pd_Ner = pd.DataFrame(columns = ["token", "NER_tag"])

for word in spacy_doc.ents:
    if pd.isna(word.label_) is False:
        pd_Ner = pd.concat([pd_Ner,pd.DataFrame.from_records([{"token" : word.text, "NER_tag" : word.label_}])],ignore_index= True)

pd_Ner.head()

         token   NER_tag
0    Liz Truss    PERSON
1           UK       GPE
2    Rationing   PRODUCT
3  superyachts  CARDINAL
4      Russian      NORP

In [27]:
displacy.render(spacy_doc, style = "ent", jupyter = True)

In [28]:
pd_token_count = pd_Ner.groupby(["token","NER_tag"]).size().reset_index(name = "count").sort_values(by = "count", ascending = False)
pd_token_count.head()

       token NER_tag  count
965  Ukraine     GPE     47
955       UK     GPE     36
329  England     GPE     32
819  Russian    NORP     20
957       US     GPE     19

In [40]:
pd_Ner_count = pd_token_count.groupby(['NER_tag'])['token'].count().sort_values(  ascending = False)
pd_Ner_count.head()

NER_tag
PERSON      376
ORG         276
GPE         134
DATE         74
CARDINAL     62
Name: token, dtype: int64

In [45]:
pd_Ner_Person = pd_token_count[pd_token_count.NER_tag == 'PERSON']
pd_Ner_Person.head()

             token NER_tag  count
257          Covid  PERSON      9
757          Putin  PERSON      8
760          Queen  PERSON      8
563      Liz Truss  PERSON      6
169  Boris Johnson  PERSON      6